version: '3'
services:
  book_shop_microservice:
    build: ./
    ports:
      - 8000:8000
    restart: always
    container_name: book_shop_microservice
    volumes:
      - . :/app/
    depends_on:
      - pgdb
  pgdb:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: root
