version: '3.5'
services:
  api:
    build: ./
    ports:
      - 8000:8000
    restart: always
    environment:
      DB_HOST: pgdb
    volumes:
      - . :/app/
    depends_on:
      - pgdb
  pgdb:
    container_name: pgDB
    image: postgres:15.3-alpine
    ports:
      - "5432:5433"
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: my_DB
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    restart: always
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
