"""add some tables

Revision ID: 38b92b06e2f0
Revises: ea6a83a8366a
Create Date: 2023-06-13 17:48:58.994673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38b92b06e2f0'
down_revision = 'ea6a83a8366a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publishing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('publishing_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shopquantity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('book_author',
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['author.id'], ),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], )
    )
    op.create_table('book_genre',
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('genre_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], )
    )
    op.create_table('orderitems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('price', sa.Numeric(), nullable=True),
    sa.Column('cost', sa.Numeric(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('salesman_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['salesman_id'], ['salesman.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('book', sa.Column('discription', sa.Text(), nullable=True))
    op.add_column('book', sa.Column('image', sa.LargeBinary(), nullable=True))
    op.add_column('book', sa.Column('publishing_id', sa.Integer(), nullable=True))
    op.add_column('book', sa.Column('shop_quantity_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'book', 'publishing', ['publishing_id'], ['id'])
    op.create_foreign_key(None, 'book', 'shopquantity', ['shop_quantity_id'], ['id'])
    op.add_column('order', sa.Column('status', sa.Boolean(), nullable=True))
    op.drop_constraint('order_salesman_id_fkey', 'order', type_='foreignkey')
    op.drop_constraint('order_book_id_fkey', 'order', type_='foreignkey')
    op.drop_column('order', 'book_id')
    op.drop_column('order', 'count')
    op.drop_column('order', 'price')
    op.drop_column('order', 'salesman_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('salesman_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('order', sa.Column('price', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('order', sa.Column('count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('order', sa.Column('book_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('order_book_id_fkey', 'order', 'book', ['book_id'], ['id'])
    op.create_foreign_key('order_salesman_id_fkey', 'order', 'salesman', ['salesman_id'], ['id'])
    op.drop_column('order', 'status')
    op.drop_constraint(None, 'book', type_='foreignkey')
    op.drop_constraint(None, 'book', type_='foreignkey')
    op.drop_column('book', 'shop_quantity_id')
    op.drop_column('book', 'publishing_id')
    op.drop_column('book', 'image')
    op.drop_column('book', 'discription')
    op.drop_table('orderitems')
    op.drop_table('book_genre')
    op.drop_table('book_author')
    op.drop_table('shopquantity')
    op.drop_table('publishing')
    # ### end Alembic commands ###
